### ISSUE TITLE
Theme doesn't apply on Linux

### ISSUE THREAD

**Issue by alexrp** [miqh/vscode-core-theme#2]
Hello,

When trying to apply the theme on Linux, nothing happens. If I set it via the command palette, the settings file isn't actually altered. Changing the file manually to say e.g. `Core (Dark)` doesn't work either; VS Code just keeps using the theme it was previously using. Applying other themes seems to work fine.

In case it matters, I'm doing this with VS Code running in WSL (and using Xming as the X server), though I think it's probably a Linux thing in general. Applying the theme works fine with VS Code running natively on Windows.

**Comment by alexrp** [comment]
Found the issue. In `~/.vscode/extensions/miqh.core-theme-0.1.0/package.json`, there are these theme entries:

```json
        "themes": [
            {
                "label": "Core (Light)",
                "uiTheme": "vs",
                "path": "themes\\light.json"
            },
            {
                "label": "Core (Dark)",
                "uiTheme": "vs-dark",
                "path": "themes\\dark.json"
            }
        ]
```

Changing those Windows-style paths to use `/` instead of `\` makes the theme work.

The bug is here: https://github.com/miqh/vscode-core-theme/blob/c6a65e4aa4689734bf28b71aacaff9513f9a83cb/src/themeManager.ts#L510

Presumably you are building the extension on Windows, so you end up embedding these Windows-style paths in the extension. You probably just want to use `/` instead since that works on all platforms.

**Comment by miqh** [comment]
Hello @alexrp,

There shouldn't be any specific references to Windows-style path separators for any areas where this theme extension builds paths. All that heavy lifting should be done by Node's `path` module. Examples below:

https://github.com/miqh/vscode-core-theme/blob/72489bb73c60bfbef29940636fa94f342e0fe006/src/themeManager.ts#L513

https://github.com/miqh/vscode-core-theme/blob/72489bb73c60bfbef29940636fa94f342e0fe006/src/themeManager.ts#L533

For the record, the `package.json` you end up seeing is rewritten dynamically. Every time you run the `Generate Themes` command, it should update the `themes` list.

I actually discovered the entire theme extension was failing to activate in the most recent version of VS Code. After patching this up and publishing 0.3.0, I tested a fresh install of the extension on an Ubuntu virtual machine and had no problem.

Please try again with the latest version and let me know how things go.
